# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 09:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('boxID', models.CharField(default=0, max_length=10, primary_key=True, serialize=False)),
                ('boxNumber', models.IntegerField(default=0)),
                ('state', models.IntegerField(default=0)),
                ('microswitch', models.IntegerField(default=0)),
                ('led', models.IntegerField(default=0)),
                ('image', models.ImageField(default=0, upload_to='')),
                ('lock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('station', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='box',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.Location'),
        ),
        migrations.AddField(
            model_name='box',
            name='userID',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
