# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usage_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='location',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='usage_info',
            name='location',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
