# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-19 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170717_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='lock',
            field=models.IntegerField(default=1),
        ),
    ]
